# Generated by Django 5.2.7 on 2026-09-01 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_verdict_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='How many days this organization allows itself to reach a verdict on a credit case before that case counts as overdue. Applies to every credit case in the organization unless the case sets its own verdict_due_days override.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
