# Generated by Django 5.2.7 on 2026-04-28 22:42

import identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_created_at_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email_domain',
            field=models.CharField(max_length=300, unique=True, validators=[identity.models.validate_domain]),
        ),
    ]
