# Generated by Django 5.2.7 on 2025-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_user_managers_alter_company_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_domain',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
