# Generated by Django 5.2.7 on 2026-04-24 19:38

import django.core.validators
import django.db.models.deletion
import processing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_user_data_upload', 'Pending User Data Upload'), ('pending_internal_review', 'Pending Internal Review'), ('pending_user_agreement', 'Pending User Agreement'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('user_rejected', 'User Rejected')], default='pending_user_data_upload', help_text='Account application status like pending, approved, rejected. Items are in order of sequence.', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Name for the account, includes organization and/or account type', max_length=100, null=True)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('loan', 'Loan')], help_text='Specify bank account type. Checking, loan, etc.', max_length=50)),
                ('users', models.ManyToManyField(blank=True, related_name='account_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuroDeCreditoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_response', models.JSONField(help_text='json response returned by API.')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('verdict', models.CharField(blank=True, max_length=1024, null=True)),
                ('account_applications', models.ManyToManyField(blank=True, related_name='buro_de_credito_reports', to='processing.accountapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_revenue_ttm', models.DecimalField(blank=True, decimal_places=2, help_text='Trailing twelve months organization revenue.', max_digits=21, null=True)),
                ('annual_expenses_ttm', models.DecimalField(blank=True, decimal_places=2, help_text='Trailing twelve months organization expenses.', max_digits=21, null=True)),
                ('account_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account_application', to='processing.accountapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAgreementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at timestamp.')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Signed at timestamp.', null=True)),
                ('file', models.FileField(help_text='The loan agreement pdf file (location).', upload_to=processing.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx'])])),
                ('account_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_agreement_documents', to='processing.accountapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='The loan verdict response: approved or rejected.', max_length=50)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, help_text='Total principal loan amount to grant.', max_digits=21, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='The annual interest rate to be paid by the user or organization.', max_digits=5, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, help_text='The monthly payment amount to be made by the user or organization. Includes principal + interest.', max_digits=21, null=True)),
                ('term', models.SmallIntegerField(blank=True, help_text='Total months for which the loan is to be repaid.', null=True)),
                ('analysis_summary', models.TextField(blank=True, help_text='Loan decision process analysis summary.', null=True)),
                ('passes_thresholds', models.JSONField(blank=True, help_text='Dict that shows if financial metrics pass thresholds along with details if not.', null=True)),
                ('loan_account_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_verdicts', to='processing.loanaccountapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanVerdictAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='The loan verdict response: approved or rejected.', max_length=50)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total loan amount to grant to the user or organization.', max_digits=21, null=True)),
                ('annual_interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='The annual interest rate to be paid by the user or organization.', max_digits=5, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The monthly payment amount to be made by the user or organization. Includes principal + interest.', max_digits=21, null=True)),
                ('term_months', models.SmallIntegerField(blank=True, help_text='Total months for which the loan is to be repaid.', null=True)),
                ('analysis_summary', models.TextField(blank=True, help_text='Loan decision process analysis summary.', null=True)),
                ('loan_account_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_verdicts_ai', to='processing.loanaccountapplication')),
            ],
        ),
    ]
