# Generated by Django 5.2.7 on 2025-12-11 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_user_completion', 'Pending User Completion'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_user_completion', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('loan', 'Loan')], max_length=50)),
                ('users', models.ManyToManyField(related_name='account_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_revenue_ttm', models.DecimalField(decimal_places=2, max_digits=21, null=True)),
                ('annual_expenses_ttm', models.DecimalField(decimal_places=2, max_digits=21, null=True)),
                ('account_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account_application', to='processing.accountapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanVerdictAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=21, null=True)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=21, null=True)),
                ('term_months', models.SmallIntegerField(null=True)),
                ('analysis_summary', models.TextField(null=True)),
                ('loan_account_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_verdict_ai', to='processing.loanaccountapplication')),
            ],
        ),
    ]
