# Generated by Django 5.2.7 on 2026-04-25 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('missing_documents', 'Missing Documents'), ('pending_ai_verdict', 'Pending AI Verdict'), ('pending_final_verdict', 'Pending Final Verdict'), ('complete', 'Complete')], default='missing_documents', help_text='Credit case status like missing docs, pending ai verdict, etc. Items are in order of sequence.', max_length=50)),
                ('verdict', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Credit case status like pending, approved, rejected. Items are in order of sequence.', max_length=50)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Requested credit line amount.', max_digits=32)),
                ('requested_term_days', models.IntegerField(blank=True, choices=[(15, '15 days'), (30, '30 days'), (45, '45 days'), (60, '60 days'), (90, '90 days')], help_text='Requested net terms (days).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Submitted for human approval timestamp.', null=True)),
                ('verdict_at', models.DateTimeField(blank=True, help_text='Final verdict timestamp after human review.', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_credit_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cases', to='customers.customer')),
            ],
        ),
    ]
