# Generated by Django 5.2.7 on 2026-06-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcase',
            name='requested_term_days',
            field=models.IntegerField(blank=True, choices=[(15, '15 days'), (30, '30 days'), (45, '45 days'), (60, '60 days'), (90, '90 days')], help_text='Requested net terms (days).', null=True),
        ),
    ]
