# Generated by Django 5.2.7 on 2026-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='type',
            field=models.CharField(default='loan', help_text='Specify bank account type. Checking, loan, etc.', max_length=50),
        ),
    ]
