# Generated by Django 5.2.7 on 2026-06-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_creditcase_requested_term_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcase',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requested credit line amount.', max_digits=32, null=True),
        ),
    ]
