# Generated by Django 5.2.7 on 2025-12-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_loanverdictai_loan_account_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
