# Generated by Django 5.2.7 on 2026-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_accountapplication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcase',
            name='currency',
            field=models.CharField(default='MXN', help_text='Currency for the requested credit line amount.', max_length=10),
        ),
    ]
