# Generated by Django 5.2.7 on 2025-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_alter_accountapplication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccountapplication',
            name='annual_expenses_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccountapplication',
            name='annual_revenue_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='term_months',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
