# Generated by Django 5.2.7 on 2026-04-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_creditcase_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcase',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN')], default='MXN', help_text='Currency for the requested credit line amount.', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditcase',
            name='requested_term_days',
            field=models.IntegerField(choices=[(15, '15 days'), (30, '30 days'), (45, '45 days'), (60, '60 days'), (90, '90 days')], default=1, help_text='Requested net terms (days).'),
            preserve_default=False,
        ),
    ]
