# Generated by Django 5.2.7 on 2026-08-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_alter_creditcase_requested_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcase',
            name='requirements_completed_at',
            field=models.DateTimeField(blank=True, help_text='When every required document for this case had been uploaded and classified. Stamped once, the first time it happens, as a record of when the file requirements were satisfied. Whether the case is complete RIGHT NOW is answered by the requirements_complete property, which is always derived from the current documents.', null=True),
        ),
    ]
