# Generated by Django 5.2.7 on 2026-09-01 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_credit_case_requirements_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcase',
            name='verdict_due_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Overrides the organization default_verdict_days for THIS case only. Null means "use the organization default", which is the normal case - set a value here only when one case genuinely needs longer or shorter than the rest.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
