# Generated by Django 5.2.7 on 2025-12-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alter_accountapplication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='status',
            field=models.CharField(choices=[('pending_user_data_upload', 'Pending User Completion'), ('pending_review', 'Pending Review'), ('pending_user_agreement', 'Pending User Agreement'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_user_data_upload', max_length=50),
        ),
    ]
