# Generated by Django 5.2.7 on 2026-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_creditcase_verdict_due_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcase',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', help_text='Currency for the requested credit line amount.', max_length=10),
        ),
    ]
