# Generated by Django 5.2.7 on 2025-12-12 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_alter_accountapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='account_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
