# Generated by Django 5.2.7 on 2025-12-17 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_alter_accountapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanverdictai',
            name='loan_account_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_verdict_ai', to='processing.loanaccountapplication'),
        ),
    ]
