# Generated by Django 5.2.7 on 2025-12-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_alter_loanverdictai_loan_account_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanverdictai',
            name='loan_account_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_verdicts_ai', to='processing.loanaccountapplication'),
        ),
    ]
