# Generated by Django 5.2.7 on 2025-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_alter_loanverdictai_loan_account_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanverdictai',
            name='analysis_summary',
            field=models.TextField(blank=True, help_text='Loan decision process analysis summary.', null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The annual interest rate to be paid by the user or company.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total loan amount to grant to the user or company.', max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The monthly payment amount to be made by the user or company.Includes principal + interest.', max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='The loan verdict response: approved or rejected.', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='term_months',
            field=models.SmallIntegerField(blank=True, help_text='Total months for which the loan is to be repaid.', null=True),
        ),
    ]
