# Generated by Django 5.2.7 on 2025-12-22 23:30

import django.core.validators
import django.db.models.deletion
import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_alter_loanverdictai_analysis_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgreementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=processing.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx'])])),
                ('account_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_agreement_documents', to='processing.accountapplication')),
            ],
        ),
    ]
