# Generated by Django 5.2.7 on 2026-01-09 19:37

import django.core.validators
import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_loanagreementdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='name',
            field=models.CharField(blank=True, help_text='Name for the account, includes company and/or account type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='status',
            field=models.CharField(choices=[('pending_user_data_upload', 'Pending User Data Upload'), ('pending_internal_review', 'Pending Internal Review'), ('pending_user_agreement', 'Pending User Agreement'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('user_rejected', 'User Rejected')], default='pending_user_data_upload', help_text='Account application status like pending, approved, rejected. Items are in order of sequence.', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountapplication',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('loan', 'Loan')], help_text='Specify bank account type. Checking, loan, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanaccountapplication',
            name='annual_expenses_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trailing twelve months company expenses.', max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccountapplication',
            name='annual_revenue_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trailing twelve months company revenue.', max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanagreementdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at timestamp.'),
        ),
        migrations.AlterField(
            model_name='loanagreementdocument',
            name='file',
            field=models.FileField(help_text='The loan agreement pdf file (location).', upload_to=processing.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='loanagreementdocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='Signed at timestamp.', null=True),
        ),
        migrations.AlterField(
            model_name='loanverdictai',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The monthly payment amount to be made by the user or company. Includes principal + interest.', max_digits=21, null=True),
        ),
    ]
