# Generated by Django 5.2.7 on 2026-02-04 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0012_alter_accountapplication_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='account_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BuroDeCreditoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_response', models.JSONField(help_text='json response returned by API.')),
                ('account_applications', models.ManyToManyField(blank=True, related_name='buro_de_credito_reports', to='processing.accountapplication')),
            ],
        ),
    ]
