# Generated by Django 5.2.7 on 2026-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_alter_accountapplication_users_burodecreditoreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='burodecreditoreport',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
