# Generated by Django 5.2.7 on 2026-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0014_burodecreditoreport_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='burodecreditoreport',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='burodecreditoreport',
            name='verdict',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
