# Generated by Django 5.2.7 on 2026-02-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0015_burodecreditoreport_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='The loan verdict response: approved or rejected.', max_length=50)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, help_text='Total principal loan amount to grant.', max_digits=21, null=True)),
                ('annual_interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='The annual interest rate to be paid by the user or company.', max_digits=5, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The monthly payment amount to be made by the user or company. Includes principal + interest.', max_digits=21, null=True)),
                ('term_months', models.SmallIntegerField(blank=True, help_text='Total months for which the loan is to be repaid.', null=True)),
                ('analysis_summary', models.TextField(blank=True, help_text='Loan decision process analysis summary.', null=True)),
                ('loan_account_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_verdicts', to='processing.loanaccountapplication')),
            ],
        ),
    ]
