# Generated by Django 5.2.7 on 2026-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0016_loanverdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanverdict',
            name='passes_thresholds',
            field=models.JSONField(blank=True, help_text='Dict that shows if financial metrics pass thresholds along with details if not.', null=True),
        ),
    ]
