# Generated by Django 5.2.7 on 2026-02-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0017_loanverdict_passes_thresholds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='annual_interest_rate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='payment_amount',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='loan_amount',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='term_months',
            new_name='term',
        ),
    ]
