# Generated by Django 5.2.7 on 2026-02-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0018_rename_annual_interest_rate_loanverdictai_interest_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanverdict',
            old_name='annual_interest_rate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='loanverdict',
            old_name='payment_amount',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='loanverdict',
            old_name='term_months',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='interest_rate',
            new_name='annual_interest_rate',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='principal',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='payment',
            new_name='payment_amount',
        ),
        migrations.RenameField(
            model_name='loanverdictai',
            old_name='term',
            new_name='term_months',
        ),
    ]
