# Generated by Django 5.2.7 on 2026-04-24 19:38

import core.validators
import django.core.validators
import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '__first__'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The uuid for this object.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_title', models.CharField(blank=True, help_text="the uploaded file's unmodified original title.", max_length=1024, null=True)),
                ('file', models.FileField(help_text='the file object that is stored.', upload_to=storage.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx']), core.validators.validate_file_size])),
                ('friendly_file_name', models.CharField(blank=True, help_text='friendly file name for readability.', max_length=512, null=True)),
                ('file_type_name', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('cashflow_statement', 'Cashflow Statement')], help_text='file type name given the choices list.', max_length=50, null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Useful JSON data that gpt extracts from files.', null=True)),
                ('mimetype', models.CharField(blank=True, help_text='mime type of the file.', max_length=1000, null=True)),
                ('account_applications', models.ManyToManyField(blank=True, related_name='upload_documents', to='processing.accountapplication')),
                ('accounts', models.ManyToManyField(blank=True, related_name='upload_documents', to='banking.account')),
            ],
        ),
    ]
