# Generated by Django 5.2.7 on 2026-04-28 21:41

import core.validators
import django.core.validators
import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the label, e.g. "sucursal".', max_length=50)),
                ('value', models.CharField(help_text='The value of the label, e.g. "sucursal MTY norte".', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_cases', models.ManyToManyField(help_text='The CreditCase that this label is associated with.', related_name='labels', to='processing.creditcase')),
                ('customers', models.ManyToManyField(help_text='The Customer that this label is associated with.', related_name='labels', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The uuid for this object.')),
                ('original_title', models.CharField(blank=True, help_text="the uploaded file's unmodified original title.", max_length=1024, null=True)),
                ('file', models.FileField(help_text='the file object that is stored.', upload_to=storage.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx']), core.validators.validate_file_size])),
                ('friendly_file_name', models.CharField(blank=True, help_text='friendly file name for readability.', max_length=512, null=True)),
                ('file_type_name', models.CharField(blank=True, choices=[('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown')], help_text='file type name given the choices list.', max_length=50, null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Useful JSON data that gpt extracts from files.', null=True)),
                ('mimetype', models.CharField(blank=True, help_text='mime type of the file.', max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('credit_case', models.ForeignKey(blank=True, help_text='the credit case the file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.creditcase')),
                ('customer', models.ForeignKey(blank=True, help_text='the customer the file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='the user that uploaded the file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDataExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField(blank=True, help_text='the raw json data extracted from the document using AI. Pydantic models can be used to parse this data into more structured formats if desired.', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text="a confidence score between 0 and 1 indicating the AI's confidence in the extracted data.", null=True)),
                ('model_version', models.CharField(blank=True, choices=[('gpt-5-nano', 'GPT-5 Nano')], help_text='the version of the AI model used for extraction, if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_document', models.ForeignKey(help_text='the UploadDocument that this extracted data is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='document_data_extracts', to='storage.uploaddocument')),
            ],
        ),
    ]
