# Generated by Django 5.2.7 on 2025-12-10 17:24

import core.validators
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to=storage.models.document_upload_to, validators=[core.validators.validate_file_size])),
                ('file_type_name', models.CharField(choices=[('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown')], max_length=50, null=True)),
                ('mimetype', models.CharField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
