# Generated by Django 5.2.7 on 2026-04-25 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('processing', '0002_creditcase'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddocument',
            name='account_applications',
        ),
        migrations.RemoveField(
            model_name='uploaddocument',
            name='accounts',
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='credit_case',
            field=models.ForeignKey(blank=True, help_text='the credit case the file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.creditcase'),
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='the customer the file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='the user that uploaded the file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
