# Generated by Django 5.2.7 on 2025-12-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='mimetype',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
