# Generated by Django 5.2.7 on 2025-12-10 22:14

import core.validators
import django.core.validators
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_document_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=storage.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx']), core.validators.validate_file_size]),
        ),
    ]
