# Generated by Django 5.2.7 on 2026-04-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_uploaddocument_account_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DocumentDataExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField(blank=True, help_text='the raw json data extracted from the document using AI. Pydantic models can be used to parse this data into more structured formats if desired.', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text="a confidence score between 0 and 1 indicating the AI's confidence in the extracted data.", null=True)),
                ('model_version', models.CharField(blank=True, choices=[('gpt-5-nano', 'GPT-5 Nano')], help_text='the version of the AI model used for extraction, if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_document', models.ForeignKey(help_text='the UploadDocument that this extracted data is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='document_data_extracts', to='storage.uploaddocument')),
            ],
        ),
    ]
