# Generated by Django 5.2.7 on 2026-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('processing', '0002_creditcase'),
        ('storage', '0003_alter_uploaddocument_file_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the label, e.g. "sucursal".', max_length=50)),
                ('value', models.CharField(help_text='The value of the label, e.g. "sucursal MTY norte".', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_cases', models.ManyToManyField(help_text='The CreditCase that this label is associated with.', related_name='labels', to='processing.creditcase')),
                ('customers', models.ManyToManyField(help_text='The Customer that this label is associated with.', related_name='labels', to='customers.customer')),
            ],
        ),
    ]
