# Generated by Django 5.2.7 on 2026-06-26 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_alter_creditcase_requested_amount'),
        ('storage', '0003_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='credit_case',
            field=models.ForeignKey(blank=True, help_text='the credit case the file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_documents', to='processing.creditcase'),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('constancia_de_situacion_fiscal', 'Constancia De Situacion Fiscal'), ('unknown', 'Unknown')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
