# Generated by Django 5.2.7 on 2026-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('cashflow_statement', 'Cashflow Statement')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
