# Generated by Django 5.2.7 on 2025-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='mimetype',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
