# Generated by Django 5.2.7 on 2026-06-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_organization'),
        ('storage', '0004_alter_uploaddocument_credit_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='the customer the file belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_documents', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('bank_statement', 'Bank Statement'), ('constancia_de_situacion_fiscal', 'Constancia De Situacion Fiscal'), ('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
