# Generated by Django 5.2.7 on 2025-12-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0021_account_account_application_alter_account_clabe_and_more'),
        ('processing', '0004_alter_accountapplication_name_and_more'),
        ('storage', '0004_alter_document_file_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='account_applications',
            field=models.ManyToManyField(related_name='documents', to='processing.accountapplication'),
        ),
        migrations.AddField(
            model_name='document',
            name='accounts',
            field=models.ManyToManyField(related_name='documents', to='banking.account'),
        ),
    ]
