# Generated by Django 5.2.7 on 2026-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_uploaddocument_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown'), ('income_statement', 'Income Statement'), ('bank_statement', 'Bank Statement'), ('balance_sheet', 'Balance Sheet'), ('constancia_de_situacion_fiscal', 'Constancia De Situacion Fiscal')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
