# Generated by Django 5.2.7 on 2025-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0022_alter_transaction_company'),
        ('processing', '0005_alter_accountapplication_status'),
        ('storage', '0006_alter_document_account_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='account_applications',
            field=models.ManyToManyField(related_name='documents', to='processing.accountapplication'),
        ),
        migrations.AlterField(
            model_name='document',
            name='accounts',
            field=models.ManyToManyField(related_name='documents', to='banking.account'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('cashflow_statement', 'Cashflow Statement'), ('income_statement', 'Income Statement'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
