# Generated by Django 5.2.7 on 2026-08-04 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('identity', '0001_initial'),
        ('storage', '0006_alter_uploaddocument_file_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(help_text='The primary key of the labeled object.')),
                ('value', models.CharField(help_text='The field value, e.g. "MTY Norte".', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='credit_cases',
        ),
        migrations.RemoveField(
            model_name='label',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='label',
            name='value',
        ),
        migrations.AddField(
            model_name='label',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The single model this custom field applies to, e.g. CreditCase.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user that created this custom field.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns this custom field definition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='The custom field name, e.g. "sucursal".', max_length=50),
        ),
        # NOTE: `uploaddocument.file_type_name`'s `choices` list is built from a Python `set`
        # (core.constants.UPLOAD_DOCUMENT_FILE_TYPE_NAMES) whose iteration order depends on the
        # process's hash seed, so `makemigrations` proposes a no-op reordering AlterField every
        # run. Deliberately excluded here since it's unrelated to this feature and carries no
        # schema/data change.
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('organization', 'content_type', 'name'), name='unique_label_per_organization_and_model'),
        ),
        migrations.AddField(
            model_name='labelvalue',
            name='content_type',
            field=models.ForeignKey(help_text='The model type of the labeled object (must match label.content_type).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='labelvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user that set this value.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labelvalue',
            name='label',
            field=models.ForeignKey(help_text='The custom field definition this value belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='storage.label'),
        ),
        migrations.AddIndex(
            model_name='labelvalue',
            index=models.Index(fields=['content_type', 'object_id'], name='storage_lab_content_0e63ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='labelvalue',
            constraint=models.UniqueConstraint(fields=('label', 'content_type', 'object_id'), name='unique_value_per_label_per_object'),
        ),
    ]
