# Generated by Django 5.2.7 on 2025-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_alter_account_users'),
        ('processing', '0006_alter_accountapplication_users'),
        ('storage', '0007_alter_document_account_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='account_applications',
            field=models.ManyToManyField(blank=True, related_name='documents', to='processing.accountapplication'),
        ),
        migrations.AlterField(
            model_name='document',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='documents', to='banking.account'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown'), ('income_statement', 'Income Statement')], max_length=50, null=True),
        ),
    ]
