# Generated by Django 5.2.7 on 2026-08-12 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('processing', '0003_alter_creditcase_requested_amount'),
        ('storage', '0007_label_dynamic_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, help_text='The kind of document this is, as a file type key (e.g. "bank_statement"). Set by the GPT classification step after upload, not by the user. Deliberately has no `choices`: valid keys live in the storage.FileType table (seeded from core/file_type_catalog.py) so organizations can eventually define their own types, which a static enum could never list.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable identifier matching UploadDocument.file_type_name, e.g. "bank_statement". Never change this after creation — documents are already stored under it. Rename label_en/label_es instead.', max_length=50)),
                ('label_en', models.CharField(help_text='Display name in English, e.g. "Bank statement".', max_length=100)),
                ('label_es', models.CharField(help_text='Display name in Spanish, e.g. "Estado de cuenta bancario".', max_length=100)),
                ('category', models.CharField(help_text='One of core.file_type_catalog.FileTypeCategory: financial, legal or other. Decides how recent a document must be to still count.', max_length=20)),
                ('months_required', models.PositiveSmallIntegerField(blank=True, help_text='How many distinct months this document must cover to satisfy a requirement (e.g. 12 monthly bank statements). Null means one document is enough regardless of period.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this type can still be added to new templates. Existing documents keep resolving either way — a type is never deleted, because documents already reference its key.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created this type (null for app-provided types).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns this type. NULL means it is an app-provided type available to every organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_types', to='identity.organization')),
            ],
            options={
                'ordering': ['label_en'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What the user calls this template, e.g. "Default" or "Clientes grandes".', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether new credit cases in this organization use this template automatically. At most one per organization.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that created this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization that owns this template.', on_delete=django.db.models.deletion.CASCADE, related_name='requirement_templates', to='identity.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='True means the case is incomplete without it. False means it is listed as optional and never blocks completion.')),
                ('source', models.CharField(choices=[('template', 'Template'), ('manual', 'Manual')], default='template', help_text='Whether this came from a template (re-syncable) or was added by hand for this case (never overwritten by a re-sync).', max_length=20)),
                ('months_required', models.PositiveSmallIntegerField(blank=True, help_text='Overrides FileType.months_required for this case only.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When this row was last added or changed by a template re-sync. Null means it has not been touched since the case was created.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user that added this requirement, or ran the sync that added it.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_case', models.ForeignKey(help_text='The credit case that needs this document.', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='processing.creditcase')),
                ('file_type', models.ForeignKey(help_text='The kind of document being asked for.', on_delete=django.db.models.deletion.PROTECT, related_name='credit_case_requirements', to='storage.filetype')),
                ('source_template', models.ForeignKey(blank=True, help_text='The template this was copied from, so a later edit of that template knows which cases it can offer to update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_requirements', to='storage.requirementtemplate')),
            ],
            options={
                'ordering': ['file_type__label_en'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='True means a credit case is incomplete without it. False means it is shown as a nice-to-have and never blocks completion.')),
                ('months_required', models.PositiveSmallIntegerField(blank=True, help_text="Overrides FileType.months_required for this template only. Null means use the file type's own value.", null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the template.')),
                ('file_type', models.ForeignKey(help_text='The kind of document being asked for.', on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='storage.filetype')),
                ('template', models.ForeignKey(help_text='The template this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storage.requirementtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_file_type_key_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('key',), name='unique_global_file_type_key'),
        ),
        migrations.AddConstraint(
            model_name='requirementtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_requirement_template_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='requirementtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='unique_default_requirement_template_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='creditcaserequirement',
            constraint=models.UniqueConstraint(fields=('credit_case', 'file_type'), name='unique_file_type_per_credit_case'),
        ),
        migrations.AddConstraint(
            model_name='requirementtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'file_type'), name='unique_file_type_per_requirement_template'),
        ),
    ]
