# Generated by Django 5.2.7 on 2025-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_document_account_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('unknown', 'Unknown'), ('cashflow_statement', 'Cashflow Statement')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
