# Generated by Django 5.2.7 on 2026-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_seed_file_types_and_backfill_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcaserequirement',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='True when a user deliberately dropped this document from this one case. The row is kept rather than deleted so the removal STICKS: a later template re-sync sees the file type is already accounted for and will not silently put it back. An excluded row is not a requirement — it is a record of one being turned off.'),
        ),
    ]
