# Generated by Django 5.2.7 on 2025-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_document_file_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('cashflow_statement', 'Cashflow Statement'), ('unknown', 'Unknown'), ('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement')], max_length=50, null=True),
        ),
    ]
