# Generated by Django 5.2.7 on 2025-12-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_alter_document_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('income_statement', 'Income Statement'), ('unknown', 'Unknown'), ('cashflow_statement', 'Cashflow Statement'), ('balance_sheet', 'Balance Sheet')], max_length=50, null=True),
        ),
    ]
