# Generated by Django 5.2.7 on 2025-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_document_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cashflow_statement', 'Cashflow Statement'), ('unrecognized', 'Unrecognized')], max_length=50, null=True),
        ),
    ]
