# Generated by Django 5.2.7 on 2025-12-22 22:09

import core.validators
import django.core.validators
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_alter_account_users'),
        ('processing', '0010_alter_loanverdictai_analysis_summary_and_more'),
        ('storage', '0016_alter_document_file_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_title', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(upload_to=storage.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx']), core.validators.validate_file_size])),
                ('file_type_name', models.CharField(blank=True, choices=[('income_statement', 'Income Statement'), ('unrecognized', 'Unrecognized'), ('balance_sheet', 'Balance Sheet'), ('cashflow_statement', 'Cashflow Statement')], max_length=50, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=1000, null=True)),
                ('account_applications', models.ManyToManyField(blank=True, related_name='UploadDocuments', to='processing.accountapplication')),
                ('accounts', models.ManyToManyField(blank=True, related_name='UploadDocuments', to='banking.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
