# Generated by Django 5.2.7 on 2025-12-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_alter_account_users'),
        ('processing', '0011_loanagreementdocument'),
        ('storage', '0017_uploaddocument_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='account_applications',
            field=models.ManyToManyField(blank=True, related_name='upload_documents', to='processing.accountapplication'),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='upload_documents', to='banking.account'),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('income_statement', 'Income Statement'), ('unrecognized', 'Unrecognized'), ('cashflow_statement', 'Cashflow Statement'), ('balance_sheet', 'Balance Sheet')], max_length=50, null=True),
        ),
    ]
