# Generated by Django 5.2.7 on 2026-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_alter_uploaddocument_account_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('unrecognized', 'Unrecognized'), ('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cashflow_statement', 'Cashflow Statement')], max_length=50, null=True),
        ),
    ]
