# Generated by Django 5.2.7 on 2026-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('income_statement', 'Income Statement'), ('cashflow_statement', 'Cashflow Statement'), ('unrecognized', 'Unrecognized'), ('balance_sheet', 'Balance Sheet')], max_length=50, null=True),
        ),
    ]
