# Generated by Django 5.2.7 on 2026-01-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocument',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('cashflow_statement', 'Cashflow Statement'), ('unrecognized', 'Unrecognized'), ('income_statement', 'Income Statement')], max_length=50, null=True),
        ),
    ]
