# Generated by Django 5.2.7 on 2026-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_uploaddocument_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Useful JSON data that gpt extracts from files.', null=True),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('income_statement', 'Income Statement'), ('bank_statement', 'Bank Statement'), ('cashflow_statement', 'Cashflow Statement'), ('balance_sheet', 'Balance Sheet')], max_length=50, null=True),
        ),
    ]
