# Generated by Django 5.2.7 on 2026-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_alter_uploaddocument_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('cashflow_statement', 'Cashflow Statement'), ('balance_sheet', 'Balance Sheet'), ('bank_statement', 'Bank Statement'), ('income_statement', 'Income Statement')], max_length=50, null=True),
        ),
    ]
