# Generated by Django 5.2.7 on 2026-01-21 00:07

import core.validators
import django.core.validators
import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocument',
            name='friendly_file_name',
            field=models.CharField(blank=True, help_text='friendly file name for readability.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The uuid for this object.'),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file',
            field=models.FileField(help_text='the file object that is stored.', upload_to=storage.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'csv', 'xml', 'json', 'docx', 'xlsx', 'pptx']), core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('bank_statement', 'Bank Statement'), ('cashflow_statement', 'Cashflow Statement')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='mimetype',
            field=models.CharField(blank=True, help_text='mime type of the file.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='original_title',
            field=models.CharField(blank=True, help_text="the uploaded file's unmodified original title.", max_length=1024, null=True),
        ),
    ]
