# Generated by Django 5.2.7 on 2026-01-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_uploaddocument_friendly_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('bank_statement', 'Bank Statement'), ('cashflow_statement', 'Cashflow Statement'), ('income_statement', 'Income Statement'), ('unknown', 'Unknown'), ('balance_sheet', 'Balance Sheet')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
