# Generated by Django 5.2.7 on 2026-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0027_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('income_statement', 'Income Statement'), ('constancia_de_situacion_fiscal', 'Constancia De Situacion Fiscal'), ('balance_sheet', 'Balance Sheet'), ('unknown', 'Unknown'), ('cashflow_statement', 'Cashflow Statement'), ('bank_statement', 'Bank Statement')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
