# Generated by Django 5.2.7 on 2026-02-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_alter_uploaddocument_file_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file_type_name',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('constancia_de_situacion_fiscal', 'Constancia De Situacion Fiscal'), ('cashflow_statement', 'Cashflow Statement')], help_text='file type name given the choices list.', max_length=50, null=True),
        ),
    ]
