# Generated by Django 5.2.7 on 2026-05-16 01:01

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name.', max_length=100)),
                ('legal_name', models.CharField(blank=True, help_text='Customer legal name recognized by government.', max_length=100, null=True)),
                ('rfc', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes for customer.', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('type', models.CharField(blank=True, choices=[('fisica', 'Persona física'), ('moral', 'Persona moral')], default='moral', help_text='Persona moral o fisica.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_postal', models.CharField(blank=True, help_text='Zip code.', max_length=12, null=True)),
                ('tipo_de_vialidad', models.CharField(blank=True, help_text='Calle, avenida, etc.', max_length=50, null=True)),
                ('nombre_de_vialidad', models.CharField(blank=True, help_text='Nombre de la calle, avenida, etc.', max_length=100, null=True)),
                ('numero_exterior', models.CharField(blank=True, help_text='Numero visible desde la calle.', max_length=100, null=True)),
                ('numero_interior', models.CharField(blank=True, help_text='Numero interior, si aplica.', max_length=100, null=True)),
                ('nombre_de_la_colonia', models.CharField(blank=True, help_text='Nombre de la colonia.', max_length=100, null=True)),
                ('nombre_de_la_localidad', models.CharField(blank=True, help_text='Nombre de la localidad, si aplica.', max_length=100, null=True)),
                ('nombre_del_municipio', models.CharField(blank=True, help_text='Nombre del municipio o demarcacion territorial.', max_length=100, null=True)),
                ('nombre_de_la_entidad_federativa', models.CharField(blank=True, help_text='Nombre del estado nacional.', max_length=100, null=True)),
                ('entre_calle', models.CharField(blank=True, help_text='Entre calle 1.', max_length=100, null=True)),
                ('y_calle', models.CharField(blank=True, help_text='Entre calle 2.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Contact first name.', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Contact last name.', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Contact email address.', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number.', max_length=128, null=True, region='MX')),
                ('role', models.CharField(blank=True, help_text='Contact role or position within the customer organization.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
