# Generated by Django 5.2.7 on 2026-05-16 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User that created this customer record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="User's Organization that created this customer record.", null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User that created this customer record.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(help_text='The customer this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='organization',
            field=models.ForeignKey(help_text="User's Organization that created this customer contact record.", on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='identity.organization'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'rfc'), name='unique_customer_rfc_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_customer_contact_email_per_organization'),
        ),
    ]
