# Generated by Django 5.2.7 on 2026-05-26 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="User's Organization that created this customer contact record.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='identity.organization'),
        ),
    ]
