# Generated by Django 5.2.7 on 2026-04-30 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Customer legal name recognized by government.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Customer name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes for customer.', max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
