# Generated by Django 5.2.7 on 2026-06-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customercontact_organization'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(help_text="User's Organization that created this customer record.", on_delete=django.db.models.deletion.CASCADE, to='identity.organization'),
        ),
    ]
