# Generated by Django 5.2.7 on 2026-04-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_legal_name_alter_customer_name_and_more'),
        ('identity', '0003_alter_organization_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="User's Organization that created this customer record.", null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.organization'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('fisica', 'Persona física'), ('moral', 'Persona moral')], default='moral', help_text='Persona moral o fisica.', max_length=20, null=True),
        ),
    ]
