# Generated by Django 5.2.7 on 2026-04-30 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_organization_alter_customer_type'),
        ('identity', '0003_alter_organization_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='organization',
            field=models.ForeignKey(default='', help_text="User's Organization that created this customer contact record.", on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='identity.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(help_text='The customer this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='email',
            field=models.EmailField(default='x@x.com', help_text='Contact email address.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'rfc'), name='unique_customer_rfc_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_customer_contact_email_per_organization'),
        ),
    ]
