# Generated by Django 5.2.7 on 2026-04-30 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customercontact_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes for customer.', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
