# Generated by Django 5.2.7 on 2026-05-01 17:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number.', max_length=128, null=True, region='MX'),
        ),
    ]
