# Generated by Django 5.2.7 on 2025-11-29 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_alter_company_email_domain_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('clabe', models.CharField(max_length=18, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(18)])),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('loan', 'Loan')], max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='identity.company')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account', to='banking.account')),
            ],
        ),
    ]
