# Generated by Django 5.2.7 on 2026-04-28 21:41

import core.date_utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('clabe', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(18)])),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('loan', 'Loan')], max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_card_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('debit_card_expiration_date', models.DateField(blank=True, default=core.date_utils.get_default_debit_card_expiration_date, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('paid_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=21)),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=50)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('payment_interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quaterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
