# Generated by Django 5.2.7 on 2026-04-28 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('identity', '0001_initial'),
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='processing.accountapplication'),
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkingaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account', to='banking.account'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='banking.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
