# Generated by Django 5.2.7 on 2026-04-24 19:39

import core.date_utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('identity', '0001_initial'),
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('clabe', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(18)])),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('loan', 'Loan')], max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='processing.accountapplication')),
                ('users', models.ManyToManyField(blank=True, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_card_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('debit_card_expiration_date', models.DateField(blank=True, default=core.date_utils.get_default_debit_card_expiration_date, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checking_account', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('paid_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=21)),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=50)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('payment_interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quaterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='identity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
