# Generated by Django 5.2.7 on 2025-11-29 20:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=datetime.datetime(2031, 11, 30, 20, 0, 1, 876473), null=True),
        ),
        migrations.AddField(
            model_name='checkingaccount',
            name='debit_card_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
