# Generated by Django 5.2.7 on 2025-12-01 23:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_checkingaccount_debit_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=datetime.datetime(2031, 12, 31, 23, 0, 27, 437939), null=True),
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('paid_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('payment_interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quaterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_payment_date', models.DateField(null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='banking.account')),
            ],
        ),
    ]
