# Generated by Django 5.2.7 on 2025-12-09 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_checkingaccount_debit_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=datetime.datetime(2031, 12, 31, 4, 40, 28, 188540), null=True),
        ),
    ]
