# Generated by Django 5.2.7 on 2025-12-09 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_remove_account_company_account_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=datetime.datetime(2031, 12, 31, 18, 25, 25, 546056), null=True),
        ),
    ]
