# Generated by Django 5.2.7 on 2025-12-09 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=datetime.datetime(2031, 12, 31, 19, 30, 28, 547958), null=True),
        ),
    ]
