# Generated by Django 5.2.7 on 2025-12-10 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0017_alter_checkingaccount_debit_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=datetime.datetime(2031, 12, 31, 0, 54, 52, 807444), null=True),
        ),
    ]
