# Generated by Django 5.2.7 on 2025-12-10 01:21

import core.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0018_alter_checkingaccount_debit_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(default=core.date_utils.get_default_debit_card_expiration_date, null=True),
        ),
    ]
