# Generated by Django 5.2.7 on 2025-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0019_alter_checkingaccount_debit_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='paid_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=21),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
    ]
