# Generated by Django 5.2.7 on 2025-12-11 17:21

import core.date_utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0020_alter_loanaccount_paid_balance_and_more'),
        ('processing', '0004_alter_accountapplication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_application',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='processing.accountapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_expiration_date',
            field=models.DateField(blank=True, default=core.date_utils.get_default_debit_card_expiration_date, null=True),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='debit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
    ]
