# Generated by Django 5.2.7 on 2025-12-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0021_account_account_application_alter_account_clabe_and_more'),
        ('identity', '0005_alter_company_email_domain_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='identity.company'),
        ),
    ]
