# Generated by Django 5.2.7 on 2025-12-12 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0022_alter_transaction_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
