# Generated by Django 5.2.7 on 2026-01-09 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_alter_account_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
