"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(jg$@e2rfi#b@t*i3pi%*&cnt4o9z-0$uerh+j^#t&ag%#h8j+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# TEMP add allowed hosts for prod
ALLOWED_HOSTS = []

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom apps
    'customers',
    'core',
    'identity',
    'integrations',
    'processing',
    'storage',
    # other
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    # django add ons
    'phonenumber_field',
]

# DRF config
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",  # Toggle on/off to remove auth
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # Toggle on/off to remove auth
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # Toggle on/off to remove auth
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,  # !This will require frontend change in setup to retrieve all items
}

SIMPLE_JWT = {
    # 🔐 Token lifetime
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # 🔁 Refresh behavior
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    # 🔑 Signing
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    # 🧾 Auth header
    "AUTH_HEADER_TYPES": ("Bearer",),

    # 👤 User
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",

    # Optional but useful
    "UPDATE_LAST_LOGIN": True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.OrganizationMiddleware',  # custom middleware to attach organization to request based on user
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration using environment variables
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('POSTGRES_DB', 'trade_credit_app_db'),
        "USER": os.getenv('POSTGRES_USER', 'trade_credit_app_user'),
        "PASSWORD": os.getenv('POSTGRES_PASSWORD', 'changeme'),
        "HOST": os.getenv('POSTGRES_HOST', 'localhost'),  # should grab value from .env
        "PORT": os.getenv('POSTGRES_PORT', '5432'),
        "ATOMIC_REQUESTS": True,
    }
}


# Default user model
AUTH_USER_MODEL = 'identity.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Celery — background jobs
# Slow work (document classification: 3 OpenAI round trips, 10-30s) is pushed onto a
# Redis queue and run by the separate `celery-worker` container, so no HTTP request and
# no database transaction ever waits on OpenAI. See app/celery.py.
#
# Defaults point at the compose service name, so nothing has to be added to .env for
# local development.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE

# Acknowledge a job only once it has FINISHED, not when it is picked up. A worker killed
# mid-classification then puts the job back on the queue instead of losing it silently.
# Safe here because re-running classification just overwrites its own output.
CELERY_TASK_ACKS_LATE = True

# Take one job at a time. The default (4) lets a worker reserve several jobs up front,
# which suits short tasks but not these: one worker could sit on four 30-second jobs
# while another idles.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# How long to wait on a single OpenAI HTTP call before giving up. Without a limit a hung
# connection pins a worker slot forever; with one it raises APITimeoutError, which the
# task retries (see storage/tasks.py).
OPENAI_REQUEST_TIMEOUT_SECONDS = float(os.getenv('OPENAI_REQUEST_TIMEOUT_SECONDS', '120'))

# How long a document may sit unclassified before the app stops calling it "in progress".
#
# Classification is three OpenAI round trips (10-30s in practice). The hard ceiling is much
# higher — each call may take OPENAI_REQUEST_TIMEOUT_SECONDS and the task retries up to
# three times — but this is not that ceiling on purpose. It is the point past which "the
# worker is down" is a likelier explanation than "it is still going", and the user is far
# better served by a file type control they can use than by a spinner that never stops.
# See storage/services/classification_state.py.
DOCUMENT_CLASSIFICATION_TIMEOUT_SECONDS = float(
    os.getenv('DOCUMENT_CLASSIFICATION_TIMEOUT_SECONDS', '300')
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Media files TODO LATER change to s3 storage
# Where uploaded files will be stored locally
MEDIA_ROOT = BASE_DIR / "media"

# URL prefix for serving media
MEDIA_URL = "/media/"

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'storage': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

