/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit-cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["credit_cases_list"];
        put?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        post: operations["credit_cases_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit-cases/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["credit_cases_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["credit_cases_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["credit_cases_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["credit_cases_partial_update"];
        trace?: never;
    };
    "/api/v1/customer-contacts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["customer_contacts_list"];
        put?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        post: operations["customer_contacts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-contacts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["customer_contacts_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["customer_contacts_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["customer_contacts_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["customer_contacts_partial_update"];
        trace?: never;
    };
    "/api/v1/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["customers_list"];
        put?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        post: operations["customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["customers_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["customers_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["customers_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["customers_partial_update"];
        trace?: never;
    };
    "/api/v1/document-data-extracts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["document_data_extracts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-data-extracts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["document_data_extracts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labels/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["labels_list"];
        put?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        post: operations["labels_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labels/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["labels_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["labels_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["labels_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["labels_partial_update"];
        trace?: never;
    };
    "/api/v1/organizations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["organizations_list"];
        put?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        post: operations["organizations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["organizations_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["organizations_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["organizations_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["organizations_partial_update"];
        trace?: never;
    };
    "/api/v1/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["upload_documents_list"];
        put?: never;
        /**
         * @description Trigger gpt process if this was the last UploadDocument required
         *     in account application process.
         */
        post: operations["upload_documents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["upload_documents_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["upload_documents_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["upload_documents_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["upload_documents_partial_update"];
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["users_list"];
        put?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        get: operations["users_retrieve"];
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        put: operations["users_update"];
        post?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Template to scope other model views to the user's (active) organization.
         *
         *     Queryset must be customized as a lookup to ensure accurate relationship lookup.
         */
        patch: operations["users_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreditCase: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /**
             * @description Credit case status like missing docs, pending ai verdict, etc. Items are in order of sequence.
             *
             *     * `missing_documents` - Missing Documents
             *     * `pending_ai_verdict` - Pending AI Verdict
             *     * `buro_de_credito_rejected` - Buro De Credito Rejected
             *     * `pending_final_verdict` - Pending Final Verdict
             *     * `complete` - Complete
             */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * @description Credit case status like pending, approved, rejected. Items are in order of sequence.
             *
             *     * `pending` - Pending
             *     * `approved` - Approved
             *     * `rejected` - Rejected
             */
            readonly verdict: components["schemas"]["VerdictEnum"];
            /**
             * Format: decimal
             * @description Requested credit line amount.
             */
            requested_amount?: string;
            /**
             * @description Currency for the requested credit line amount.
             *
             *     * `MXN` - MXN
             */
            currency?: components["schemas"]["CurrencyEnum"];
            /**
             * @description Requested net terms (days).
             *
             *     * `15` - 15 days
             *     * `30` - 30 days
             *     * `45` - 45 days
             *     * `60` - 60 days
             *     * `90` - 90 days
             */
            requested_term_days: components["schemas"]["RequestedTermDaysEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description Submitted for human approval timestamp.
             */
            readonly submitted_at: string | null;
            /**
             * Format: date-time
             * @description Final verdict timestamp after human review.
             */
            readonly verdict_at: string | null;
            /** Format: uri */
            customer: string;
            /** Format: uri */
            readonly organization: string;
        };
        /**
         * @description * `MXN` - MXN
         * @enum {string}
         */
        CurrencyEnum: "MXN";
        Customer: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /** @description Customer name. */
            name: string;
            /** @description Customer legal name recognized by government. */
            readonly legal_name: string | null;
            /** @description Registro Federal de Contribuyentes for customer. */
            readonly rfc: string | null;
            /**
             * @description Persona moral o fisica.
             *
             *     * `fisica` - Persona física
             *     * `moral` - Persona moral
             */
            readonly type: (components["schemas"]["TypeEnum"] | components["schemas"]["NullEnum"]) | null;
            /** @description Nombre de la calle, avenida, etc. */
            readonly nombre_de_vialidad: string | null;
            /** @description Zip code. */
            readonly codigo_postal: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /**
             * Format: uri
             * @description User's Organization that created this customer record.
             */
            readonly organization: string;
            /**
             * Format: uri
             * @description User that created this customer record.
             */
            readonly created_by: string | null;
            readonly customer_contacts: string[];
        };
        CustomerContact: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /** @description Contact first name. */
            first_name?: string | null;
            /** @description Contact last name. */
            last_name?: string | null;
            /**
             * Format: email
             * @description Contact email address.
             */
            email: string;
            /** @description Contact phone number. */
            phone_number?: string | null;
            /** @description Contact role or position within the customer organization. */
            role?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /**
             * Format: uri
             * @description User that created this customer record.
             */
            readonly created_by: string | null;
            /**
             * Format: uri
             * @description The customer this contact belongs to.
             */
            customer: string;
            /**
             * Format: uri
             * @description User's Organization that created this customer contact record.
             */
            readonly organization: string | null;
        };
        DocumentDataExtract: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /** @description the raw json data extracted from the document using AI. Pydantic models can be used to parse this data into more structured formats if desired. */
            readonly raw_json: unknown;
            /**
             * Format: double
             * @description a confidence score between 0 and 1 indicating the AI's confidence in the extracted data.
             */
            readonly confidence_score: number | null;
            /**
             * @description the version of the AI model used for extraction, if applicable.
             *
             *     * `gpt-5-nano` - GPT-5 Nano
             */
            readonly model_version: (components["schemas"]["ModelVersionEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uri */
            readonly upload_document: string;
        };
        /**
         * @description * `cashflow_statement` - Cashflow Statement
         *     * `unknown` - Unknown
         * @enum {string}
         */
        FileTypeNameEnum: "cashflow_statement" | "unknown";
        Label: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /** @description The name of the label, e.g. "sucursal". */
            name: string;
            /** @description The value of the label, e.g. "sucursal MTY norte". */
            value: string;
            /** Format: date-time */
            readonly created_at: string;
            /** @description The CreditCase that this label is associated with. */
            credit_cases: string[];
            /** @description The Customer that this label is associated with. */
            customers: string[];
        };
        /**
         * @description * `gpt-5-nano` - GPT-5 Nano
         * @enum {string}
         */
        ModelVersionEnum: "gpt-5-nano";
        /** @enum {unknown} */
        NullEnum: null;
        Organization: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            name: string;
            email_domain: string;
            readonly users: string[];
        };
        PaginatedCreditCaseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CreditCase"][];
        };
        PaginatedCustomerContactList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CustomerContact"][];
        };
        PaginatedCustomerList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Customer"][];
        };
        PaginatedDocumentDataExtractList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DocumentDataExtract"][];
        };
        PaginatedLabelList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Label"][];
        };
        PaginatedOrganizationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Organization"][];
        };
        PaginatedUploadDocumentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UploadDocument"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        PatchedCreditCase: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            /**
             * @description Credit case status like missing docs, pending ai verdict, etc. Items are in order of sequence.
             *
             *     * `missing_documents` - Missing Documents
             *     * `pending_ai_verdict` - Pending AI Verdict
             *     * `buro_de_credito_rejected` - Buro De Credito Rejected
             *     * `pending_final_verdict` - Pending Final Verdict
             *     * `complete` - Complete
             */
            readonly status?: components["schemas"]["StatusEnum"];
            /**
             * @description Credit case status like pending, approved, rejected. Items are in order of sequence.
             *
             *     * `pending` - Pending
             *     * `approved` - Approved
             *     * `rejected` - Rejected
             */
            readonly verdict?: components["schemas"]["VerdictEnum"];
            /**
             * Format: decimal
             * @description Requested credit line amount.
             */
            requested_amount?: string;
            /**
             * @description Currency for the requested credit line amount.
             *
             *     * `MXN` - MXN
             */
            currency?: components["schemas"]["CurrencyEnum"];
            /**
             * @description Requested net terms (days).
             *
             *     * `15` - 15 days
             *     * `30` - 30 days
             *     * `45` - 45 days
             *     * `60` - 60 days
             *     * `90` - 90 days
             */
            requested_term_days?: components["schemas"]["RequestedTermDaysEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /**
             * Format: date-time
             * @description Submitted for human approval timestamp.
             */
            readonly submitted_at?: string | null;
            /**
             * Format: date-time
             * @description Final verdict timestamp after human review.
             */
            readonly verdict_at?: string | null;
            /** Format: uri */
            customer?: string;
            /** Format: uri */
            readonly organization?: string;
        };
        PatchedCustomer: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            /** @description Customer name. */
            name?: string;
            /** @description Customer legal name recognized by government. */
            readonly legal_name?: string | null;
            /** @description Registro Federal de Contribuyentes for customer. */
            readonly rfc?: string | null;
            /**
             * @description Persona moral o fisica.
             *
             *     * `fisica` - Persona física
             *     * `moral` - Persona moral
             */
            readonly type?: (components["schemas"]["TypeEnum"] | components["schemas"]["NullEnum"]) | null;
            /** @description Nombre de la calle, avenida, etc. */
            readonly nombre_de_vialidad?: string | null;
            /** @description Zip code. */
            readonly codigo_postal?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /**
             * Format: uri
             * @description User's Organization that created this customer record.
             */
            readonly organization?: string;
            /**
             * Format: uri
             * @description User that created this customer record.
             */
            readonly created_by?: string | null;
            readonly customer_contacts?: string[];
        };
        PatchedCustomerContact: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            /** @description Contact first name. */
            first_name?: string | null;
            /** @description Contact last name. */
            last_name?: string | null;
            /**
             * Format: email
             * @description Contact email address.
             */
            email?: string;
            /** @description Contact phone number. */
            phone_number?: string | null;
            /** @description Contact role or position within the customer organization. */
            role?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /**
             * Format: uri
             * @description User that created this customer record.
             */
            readonly created_by?: string | null;
            /**
             * Format: uri
             * @description The customer this contact belongs to.
             */
            customer?: string;
            /**
             * Format: uri
             * @description User's Organization that created this customer contact record.
             */
            readonly organization?: string | null;
        };
        PatchedLabel: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            /** @description The name of the label, e.g. "sucursal". */
            name?: string;
            /** @description The value of the label, e.g. "sucursal MTY norte". */
            value?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** @description The CreditCase that this label is associated with. */
            credit_cases?: string[];
            /** @description The Customer that this label is associated with. */
            customers?: string[];
        };
        PatchedOrganization: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            name?: string;
            email_domain?: string;
            readonly users?: string[];
        };
        PatchedUploadDocument: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            /** Format: date-time */
            readonly uploaded_at?: string;
            /** @description the uploaded file's unmodified original title. */
            readonly original_title?: string | null;
            /**
             * Format: uri
             * @description the file object that is stored.
             */
            file?: string;
            /** @description friendly file name for readability. */
            readonly friendly_file_name?: string | null;
            /**
             * @description file type name given the choices list.
             *
             *     * `cashflow_statement` - Cashflow Statement
             *     * `unknown` - Unknown
             */
            readonly file_type_name?: (components["schemas"]["FileTypeNameEnum"] | components["schemas"]["NullEnum"]) | null;
            /** @description mime type of the file. */
            readonly mimetype?: string | null;
            /** @description Useful JSON data that gpt extracts from files. */
            readonly extracted_data?: unknown;
            /**
             * Format: uri
             * @description the credit case the file belongs to.
             */
            credit_case?: string | null;
            /**
             * Format: uri
             * @description the customer the file belongs to.
             */
            customer?: string | null;
        };
        PatchedUser: {
            /** Format: uri */
            readonly url?: string;
            readonly id?: number;
            /** Format: email */
            email?: string;
            password?: string;
            /** Format: date-time */
            readonly date_joined?: string;
            readonly first_name?: string;
            readonly last_name?: string;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            readonly is_superuser?: boolean;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            readonly is_staff?: boolean;
            /**
             * Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            readonly is_active?: boolean;
            readonly organizations?: string[];
        };
        /**
         * @description * `15` - 15 days
         *     * `30` - 30 days
         *     * `45` - 45 days
         *     * `60` - 60 days
         *     * `90` - 90 days
         * @enum {integer}
         */
        RequestedTermDaysEnum: 15 | 30 | 45 | 60 | 90;
        /**
         * @description * `missing_documents` - Missing Documents
         *     * `pending_ai_verdict` - Pending AI Verdict
         *     * `buro_de_credito_rejected` - Buro De Credito Rejected
         *     * `pending_final_verdict` - Pending Final Verdict
         *     * `complete` - Complete
         * @enum {string}
         */
        StatusEnum: "missing_documents" | "pending_ai_verdict" | "buro_de_credito_rejected" | "pending_final_verdict" | "complete";
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /**
         * @description * `fisica` - Persona física
         *     * `moral` - Persona moral
         * @enum {string}
         */
        TypeEnum: "fisica" | "moral";
        UploadDocument: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /** Format: date-time */
            readonly uploaded_at: string;
            /** @description the uploaded file's unmodified original title. */
            readonly original_title: string | null;
            /**
             * Format: uri
             * @description the file object that is stored.
             */
            file: string;
            /** @description friendly file name for readability. */
            readonly friendly_file_name: string | null;
            /**
             * @description file type name given the choices list.
             *
             *     * `cashflow_statement` - Cashflow Statement
             *     * `unknown` - Unknown
             */
            readonly file_type_name: (components["schemas"]["FileTypeNameEnum"] | components["schemas"]["NullEnum"]) | null;
            /** @description mime type of the file. */
            readonly mimetype: string | null;
            /** @description Useful JSON data that gpt extracts from files. */
            readonly extracted_data: unknown;
            /**
             * Format: uri
             * @description the credit case the file belongs to.
             */
            credit_case?: string | null;
            /**
             * Format: uri
             * @description the customer the file belongs to.
             */
            customer?: string | null;
        };
        User: {
            /** Format: uri */
            readonly url: string;
            readonly id: number;
            /** Format: email */
            email: string;
            password: string;
            /** Format: date-time */
            readonly date_joined: string;
            readonly first_name: string;
            readonly last_name: string;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            readonly is_superuser: boolean;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            readonly is_staff: boolean;
            /**
             * Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            readonly is_active: boolean;
            readonly organizations: string[];
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        VerdictEnum: "pending" | "approved" | "rejected";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    credit_cases_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCreditCaseList"];
                };
            };
        };
    };
    credit_cases_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditCase"];
                "application/x-www-form-urlencoded": components["schemas"]["CreditCase"];
                "multipart/form-data": components["schemas"]["CreditCase"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCase"];
                };
            };
        };
    };
    credit_cases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this credit case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCase"];
                };
            };
        };
    };
    credit_cases_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this credit case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditCase"];
                "application/x-www-form-urlencoded": components["schemas"]["CreditCase"];
                "multipart/form-data": components["schemas"]["CreditCase"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCase"];
                };
            };
        };
    };
    credit_cases_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this credit case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    credit_cases_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this credit case. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCreditCase"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCreditCase"];
                "multipart/form-data": components["schemas"]["PatchedCreditCase"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCase"];
                };
            };
        };
    };
    customer_contacts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomerContactList"];
                };
            };
        };
    };
    customer_contacts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerContact"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerContact"];
                "multipart/form-data": components["schemas"]["CustomerContact"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerContact"];
                };
            };
        };
    };
    customer_contacts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer contact. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerContact"];
                };
            };
        };
    };
    customer_contacts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer contact. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerContact"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerContact"];
                "multipart/form-data": components["schemas"]["CustomerContact"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerContact"];
                };
            };
        };
    };
    customer_contacts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer contact. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customer_contacts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer contact. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomerContact"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomerContact"];
                "multipart/form-data": components["schemas"]["PatchedCustomerContact"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerContact"];
                };
            };
        };
    };
    customers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomerList"];
                };
            };
        };
    };
    customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Customer"];
                "application/x-www-form-urlencoded": components["schemas"]["Customer"];
                "multipart/form-data": components["schemas"]["Customer"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Customer"];
                "application/x-www-form-urlencoded": components["schemas"]["Customer"];
                "multipart/form-data": components["schemas"]["Customer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomer"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomer"];
                "multipart/form-data": components["schemas"]["PatchedCustomer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    document_data_extracts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentDataExtractList"];
                };
            };
        };
    };
    document_data_extracts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this document data extract. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDataExtract"];
                };
            };
        };
    };
    labels_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLabelList"];
                };
            };
        };
    };
    labels_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Label"];
                "application/x-www-form-urlencoded": components["schemas"]["Label"];
                "multipart/form-data": components["schemas"]["Label"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
        };
    };
    labels_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this label. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
        };
    };
    labels_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this label. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Label"];
                "application/x-www-form-urlencoded": components["schemas"]["Label"];
                "multipart/form-data": components["schemas"]["Label"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
        };
    };
    labels_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this label. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    labels_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this label. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLabel"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLabel"];
                "multipart/form-data": components["schemas"]["PatchedLabel"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
        };
    };
    organizations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrganizationList"];
                };
            };
        };
    };
    organizations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Organization"];
                "application/x-www-form-urlencoded": components["schemas"]["Organization"];
                "multipart/form-data": components["schemas"]["Organization"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    organizations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this organization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    organizations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this organization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Organization"];
                "application/x-www-form-urlencoded": components["schemas"]["Organization"];
                "multipart/form-data": components["schemas"]["Organization"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    organizations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this organization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    organizations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this organization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrganization"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOrganization"];
                "multipart/form-data": components["schemas"]["PatchedOrganization"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_documents_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUploadDocumentList"];
                };
            };
        };
    };
    upload_documents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadDocument"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadDocument"];
                "multipart/form-data": components["schemas"]["UploadDocument"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocument"];
                };
            };
        };
    };
    upload_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this upload document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocument"];
                };
            };
        };
    };
    upload_documents_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this upload document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadDocument"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadDocument"];
                "multipart/form-data": components["schemas"]["UploadDocument"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocument"];
                };
            };
        };
    };
    upload_documents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this upload document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_documents_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this upload document. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUploadDocument"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUploadDocument"];
                "multipart/form-data": components["schemas"]["PatchedUploadDocument"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocument"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
